name: "PSEG Long Island Automation"
url: "https://github.com/grega1303/psegli3"
maintainer: "Dan was here"
description: "Automated PSEG Long Island login and energy data retrieval"
version: "2.5.0"
homeassistant: "2024.8.0"
